import { WeddingGift } from '@/types/wedding';

export const INITIAL_MOCK_GIFTS: WeddingGift[] = [
  {
    id: 'gift_001',
    guest_name: 'ឯកឧត្តម សុខ ចិន្តា & លោកជំទាវ',
    guest_phone: '012 888 999',
    side: 'groom',
    amount: 200,
    currency: 'USD',
    payment_method: 'Cash',
    receipt_url: null,
    wishes: 'សូមជូនពរគូស្វាមីភរិយាថ្មី មានសុភមង្គល និងស្រឡាញ់គ្នារហូតដល់ចាស់កោងខ្នង។',
    status: 'approved',
    approved_by: 'admin_reception',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'gift_002',
    guest_name: 'លោកស្រី គង់ ម៉ាលីស',
    guest_phone: '098 765 432',
    side: 'bride',
    amount: 200000,
    currency: 'KHR',
    payment_method: 'ABA KHQR',
    receipt_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    wishes: 'រីករាយថ្ងៃអាពាហ៍ពិពាហ៍! ជូនពររកស៊ីមានបាន សុខសប្បាយគ្រប់ប្រការ។',
    status: 'approved',
    approved_by: 'admin_reception',
    created_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
  },
  {
    id: 'gift_003',
    guest_name: 'លោក ចាន់ រស្មី & ភរិយា',
    guest_phone: '017 333 444',
    side: 'both',
    amount: 100,
    currency: 'USD',
    payment_method: 'Bakong',
    receipt_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    wishes: 'សូមឱ្យស្រឡាញ់គ្នាផ្អែមល្ហែម ឆាប់បានកូនពូជល្អតពូជពង្ស។',
    status: 'approved',
    approved_by: 'admin_reception',
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'gift_004',
    guest_name: 'លោក អ៊ុំ សុវណ្ណ (ពូ)',
    guest_phone: '011 222 111',
    side: 'groom',
    amount: 400000,
    currency: 'KHR',
    payment_method: 'Cash',
    receipt_url: null,
    wishes: 'ជ័យជោគ សិរីសួស្តី ត្រជាក់ត្រជុំដូចទឹកអម្រឹត។',
    status: 'approved',
    approved_by: 'admin_reception',
    created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'gift_005',
    guest_name: 'កញ្ញា លី សុជាតា',
    guest_phone: '085 999 123',
    side: 'bride',
    amount: 50,
    currency: 'USD',
    payment_method: 'ABA KHQR',
    receipt_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    wishes: 'Congratulations Thida & Piseth! May your love grow stronger each day!',
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'gift_006',
    guest_name: 'លោក ហេង វិបុល',
    guest_phone: '070 555 888',
    side: 'groom',
    amount: 100,
    currency: 'USD',
    payment_method: 'ABA KHQR',
    receipt_url: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    wishes: 'ជូនពរប្អូនប្រុសប្អូនស្រី រីករាយរាប់រយឆ្នាំ!',
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
];
